dist: xenial
language: go
go: '1.11'
services:
- docker
go_import_path: go.mozilla.org/autograph

before_install:
- make install-dev-deps

script:
- make generate install
- make dummy-statsd &
- make build-container

# Run a synthetic monitoring test against the container
- make run-container

- cd $GOPATH/src/go.mozilla.org/autograph/tools/autograph-monitor && make && ./autograph-monitor
